[package]
name = "bootty-terminal"
edition.workspace = true

[dependencies]
portable-pty.workspace = true
anyhow.workspace = true
base64.workspace = true
libghostty-vt.workspace = true
memchr.workspace = true
png.workspace = true

[dev-dependencies]
libc = "0.2"
pretty_assertions.workspace = true
proptest.workspace = true
proptest-derive.workspace = true
rstest.workspace = true
unicode-width.workspace = true

[[test]]
name = "terminal_engine"
path = "tests/terminal_engine/main.rs"
