[package]
name = "bootty-tmux"
version.workspace = true
edition.workspace = true

[features]
default = ["app"]
app = ["bootty-mux/app"]

[dependencies]
bootty-mux = { path = "../bootty-mux", default-features = false }
bootty-workspace-hack = { version = "0.1", path = "../bootty-workspace-hack" }

[dev-dependencies]
anyhow.workspace = true
assert_fs.workspace = true
bootty-identity = { path = "../bootty-identity" }
bootty-mux-model = { path = "../bootty-mux-model" }
pretty_assertions.workspace = true
proptest.workspace = true
proptest-derive.workspace = true
rstest.workspace = true

[lints]
workspace = true
