[package]
name = "bootty-identity"
edition.workspace = true

[features]
bootty-dev = []

[lints]
workspace = true

[dependencies]
bootty-workspace-hack = { version = "0.1", path = "../bootty-workspace-hack" }
thiserror.workspace = true

[dev-dependencies]
pretty_assertions.workspace = true
rstest.workspace = true
