[package]
name = "bootty-daemon"
version.workspace = true
edition.workspace = true

[[bin]]
name = "bootty-daemon"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
bootty-config = { path = "../bootty-config" }
bootty-git = { path = "../bootty-git" }
bootty-host = { path = "../bootty-host" }
bootty-mux = { path = "../bootty-mux", default-features = false }
rusqlite.workspace = true
serde_json.workspace = true

[dev-dependencies]
base64.workspace = true
rstest.workspace = true
assert_fs.workspace = true
pretty_assertions.workspace = true
rmux-sdk.workspace = true
tokio = { workspace = true, features = ["rt", "rt-multi-thread", "macros", "sync"] }

[lints]
workspace = true
