[package]
name = "bootty-tests"
version.workspace = true
edition.workspace = true
publish = false
autolib = false
autobins = false
autoexamples = false
autobenches = false
autotests = false

[dependencies]

[dev-dependencies]
bootty-config = { path = "../crates/bootty-config" }
bootty-mux = { path = "../crates/bootty-mux" }
pretty_assertions.workspace = true
proptest.workspace = true
proptest-derive.workspace = true
rstest.workspace = true

[lints]
workspace = true

[[test]]
name = "identity_paths"
path = "identity_paths.rs"
