[package]
name = "bootty-remote"
version.workspace = true
edition.workspace = true

[features]
default = ["app"]
app = ["bootty-mux/app"]
terminfo = []

[dependencies]
bootty-host = { path = "../bootty-host" }
bootty-mux = { path = "../bootty-mux", default-features = false }
bootty-workspace-hack = { version = "0.1", path = "../bootty-workspace-hack" }

[dev-dependencies]
anyhow.workspace = true
assert_fs.workspace = true
bootty-mux-model = { path = "../bootty-mux-model" }
pretty_assertions.workspace = true
proptest.workspace = true
proptest-derive.workspace = true
static_assertions.workspace = true

[dev-dependencies.base64]
workspace = true

[dev-dependencies.serde_json]
workspace = true
[lints]
workspace = true
