[package]
name = "bootty-rmux"
version.workspace = true
edition.workspace = true

[features]
default = ["app"]
app = ["bootty-mux/app"]

[dependencies]
bootty-mux = { path = "../bootty-mux", default-features = false }
bootty-workspace-hack = { version = "0.1", path = "../bootty-workspace-hack" }

[dev-dependencies]
anyhow.workspace = true
assert_fs.workspace = true
bootty-identity = { path = "../bootty-identity" }
bootty-mux-model = { path = "../bootty-mux-model" }
bootty-surface = { path = "../bootty-surface" }
bootty-terminal = { path = "../bootty-terminal" }
pretty_assertions.workspace = true
proptest.workspace = true
proptest-derive.workspace = true
rstest.workspace = true
static_assertions.workspace = true
bootty-runtime = { path = "../bootty-runtime" }
tokio = { workspace = true, features = ["rt", "rt-multi-thread", "macros", "sync"] }

[dev-dependencies.base64]
workspace = true

[dev-dependencies.rmux-server]
workspace = true

[dev-dependencies.serde_json]
workspace = true
[lints]
workspace = true
