[package]
name = "bootty"
version.workspace = true
edition.workspace = true
build = "build.rs"

[features]
bootty-dev = ["bootty-ui/bootty-dev", "bootty-config/bootty-dev", "bootty-control/bootty-dev"]

[[bin]]
name = "bootty"
path = "src/main.rs"

[dependencies]
bootty-config = { path = "../bootty-config" }
bootty-host = { path = "../bootty-host" }
bootty-terminal = { path = "../bootty-terminal" }
bootty-ui = { path = "../bootty-ui" }
anyhow.workspace = true
base64.workspace = true
bootty-control = { path = "../bootty-control" }
bootty-mux = { path = "../bootty-mux" }
serde_json.workspace = true
clap.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["rt", "signal"] }

[build-dependencies]
embed-resource.workspace = true

[dev-dependencies]
proptest.workspace = true
assert_fs.workspace = true
pretty_assertions.workspace = true
rstest.workspace = true

[lints]
workspace = true
