[package]
name = "bootty-write"
edition.workspace = true

[lints]
workspace = true

[dependencies]
tempfile.workspace = true

[target.'cfg(windows)'.dependencies]
winsafe.workspace = true

[dev-dependencies]
assert_fs.workspace = true
pretty_assertions.workspace = true
proptest.workspace = true
proptest-derive.workspace = true
rstest.workspace = true
