[package]
name = "bootty-config"
edition.workspace = true

[features]
bootty-dev = []

[lints]
workspace = true

[dependencies]
num-traits.workspace = true
plist.workspace = true
sha2.workspace = true
tempfile.workspace = true
bootty-write = { path = "../bootty-write" }
serde.workspace = true
serde_json = { workspace = true, features = ["preserve_order"] }
strum.workspace = true
toml_edit.workspace = true
thiserror.workspace = true

[dev-dependencies]
assert_fs.workspace = true
indoc.workspace = true
pretty_assertions.workspace = true
proptest.workspace = true
rstest.workspace = true
