[package]
name = "bootty-config"
edition.workspace = true

[lints]
workspace = true

[dependencies]
bootty-write = { path = "../bootty-write" }
serde.workspace = true
toml_edit.workspace = true
thiserror.workspace = true
strum.workspace = true

[dev-dependencies]
assert_fs.workspace = true
indoc.workspace = true
pretty_assertions.workspace = true
rstest.workspace = true

[features]
bootty-dev = []
