[package]
name = "bootty-font"
edition.workspace = true

[lints]
workspace = true

[dependencies]

bootty-config = { path = "../bootty-config" }
bootty-workspace-hack = { version = "0.1", path = "../bootty-workspace-hack" }

[dev-dependencies]
pretty_assertions.workspace = true
proptest.workspace = true
rstest.workspace = true
