[package]
name = "bootty-extension"
version.workspace = true
edition.workspace = true

[dependencies]
bootty-command = { path = "../bootty-command" }
bootty-control = { path = "../bootty-control" }
bootty-config = { path = "../bootty-config" }
bootty-item = { path = "../bootty-item" }
bootty-write = { path = "../bootty-write" }
bootty-workspace-hack = { version = "0.1", path = "../bootty-workspace-hack" }
mlua = { version = "0.12.0", features = ["luau", "serialize"] }
notify.workspace = true
process-wrap.workspace = true
serde.workspace = true
serde_json.workspace = true
starship-battery.workspace = true
sysinfo.workspace = true

[lints]
workspace = true

[dev-dependencies]
assert_fs.workspace = true
pretty_assertions.workspace = true
proptest.workspace = true
rstest.workspace = true
static_assertions.workspace = true
