import type { TerminalBackend, TerminalResize } from "./terminal-api";
import type { WebCell, WebColor, WebTerminalFrame } from "./terminal-types";

const CELL_WIDTH = 9;
const CELL_HEIGHT = 18;
const PROMPT = "$ ";
const BACKGROUND: WebColor = { r: 17, g: 18, b: 26 };
const FOREGROUND: WebColor = { r: 192, g: 202, b: 245 };
const MUTED: WebColor = { r: 169, g: 177, b: 214 };
const GREEN: WebColor = { r: 158, g: 206, b: 106 };
const BLUE: WebColor = { r: 122, g: 162, b: 247 };
const RED: WebColor = { r: 247, g: 118, b: 142 };

type Line = {
  text: string;
  fg?: WebColor;
};

type Cursor = {
  x: number;
  y: number;
  color: WebColor | null;
};

export function createFakeShellBackend(): TerminalBackend {
  const shell = new FakeShell();
  return {
    label: "static fake shell backend",
    start: () => shell.start(),
    readFrame: () => shell.frame(),
    resize: (request) => shell.resize(request),
    write: (input) => shell.write(input),
  };
}

class FakeShell {
  private cols = 80;
  private rows = 24;
  private input = "";
  private readonly lines: Line[] = [];

  async start(): Promise<WebTerminalFrame> {
    if (this.lines.length === 0) {
      this.lines.push(
        { text: "Bootty static web demo", fg: BLUE },
        { text: "This terminal is backed by an in-browser fake shell.", fg: MUTED },
        { text: "Try: help, echo hello, date, ls, cat README.md, clear", fg: MUTED },
        { text: "" },
      );
    }
    return this.frame();
  }

  async resize(request: TerminalResize): Promise<WebTerminalFrame> {
    this.cols = Math.max(1, request.cols);
    this.rows = Math.max(1, request.rows);
    return this.frame();
  }

  async write(input: string): Promise<void> {
    for (const char of input) {
      this.accept(char);
    }
  }

  async frame(): Promise<WebTerminalFrame> {
    const rendered = wrapLines([...this.lines, { text: `${PROMPT}${this.input}`, fg: FOREGROUND }], this.cols);
    const visible = rendered.slice(-this.rows);
    const cells: WebCell[] = [];

    for (let y = 0; y < visible.length; y += 1) {
      const line = visible[y];
      for (let x = 0; x < line.text.length && x < this.cols; x += 1) {
        cells.push(cell(x, y, line.text[x], line.fg ?? FOREGROUND));
      }
    }

    return {
      cols: this.cols,
      rows: this.rows,
      cellWidth: CELL_WIDTH,
      cellHeight: CELL_HEIGHT,
      colors: {
        background: BACKGROUND,
        foreground: FOREGROUND,
        cursor: FOREGROUND,
      },
      cursor: cursorFor(visible, this.cols),
      cells,
    };
  }

  private accept(char: string): void {
    switch (char) {
      case "\r":
      case "\n":
        this.submit();
        return;
      case "\x7f":
        this.input = this.input.slice(0, -1);
        return;
      case "\t":
        this.input += "  ";
        return;
      case "\x1b":
        return;
      default:
        if (char >= " ") {
          this.input += char;
        }
    }
  }

  private submit(): void {
    const command = this.input.trim();
    this.lines.push({ text: `${PROMPT}${this.input}` });
    this.input = "";

    if (command.length === 0) {
      return;
    }
    if (command === "clear") {
      this.lines.length = 0;
      return;
    }

    this.lines.push(...runCommand(command));
  }
}

function runCommand(command: string): Line[] {
  const [name, ...args] = splitWords(command);
  switch (name) {
    case "help":
      return [
        { text: "available commands:", fg: GREEN },
        { text: "  help              show this help" },
        { text: "  echo <text>       print text" },
        { text: "  date              print browser time" },
        { text: "  ls                list demo files" },
        { text: "  cat README.md     print demo readme" },
        { text: "  clear             clear the screen" },
      ];
    case "echo":
      return [{ text: args.join(" ") }];
    case "date":
      return [{ text: new Date().toString() }];
    case "ls":
      return [
        { text: "README.md", fg: BLUE },
        { text: "package.json", fg: BLUE },
        { text: "src-ui/", fg: BLUE },
      ];
    case "cat":
      if (args[0] === "README.md") {
        return [
          { text: "Bootty is a terminal rendering demo.", fg: GREEN },
          { text: "This GitHub Pages build runs without Tauri or a PTY." },
          { text: "The terminal frame is generated by fake-shell-backend.ts." },
        ];
      }
      return [{ text: `cat: ${args[0] ?? ""}: No such file`, fg: RED }];
    default:
      return [{ text: `${name}: command not found`, fg: RED }];
  }
}

function splitWords(command: string): string[] {
  return command.split(/\s+/).filter((word) => word.length > 0);
}

function wrapLines(lines: Line[], cols: number): Line[] {
  const wrapped: Line[] = [];
  for (const line of lines) {
    if (line.text.length === 0) {
      wrapped.push(line);
      continue;
    }
    for (let start = 0; start < line.text.length; start += cols) {
      wrapped.push({ text: line.text.slice(start, start + cols), fg: line.fg });
    }
  }
  return wrapped;
}

function cursorFor(lines: Line[], cols: number): Cursor {
  const lastLine = lines.at(-1);
  if (!lastLine) {
    return { x: 0, y: 0, color: null };
  }
  return {
    x: Math.min(lastLine.text.length, cols - 1),
    y: Math.max(0, lines.length - 1),
    color: null,
  };
}

function cell(x: number, y: number, text: string, fg: WebColor): WebCell {
  return {
    x,
    y,
    text,
    fg,
    bg: null,
    style: {
      bold: false,
      italic: false,
      faint: false,
      blink: false,
      inverse: false,
      invisible: false,
      strikethrough: false,
      overline: false,
      underline: false,
    },
  };
}