[package]
name = "bootty-host"
version.workspace = true
edition.workspace = true

[dependencies]
notify.workspace = true
bytes.workspace = true
h2.workspace = true
http.workspace = true
tokio-rustls.workspace = true
quinn.workspace = true
rcgen.workspace = true
rustls.workspace = true
portable-pty.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "net", "io-util", "sync", "time", "macros", "process"] }
anyhow.workspace = true
base64.workspace = true
bootty-config = { path = "../bootty-config" }
bootty-write = { path = "../bootty-write" }
getrandom.workspace = true
rmux-os.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tempfile.workspace = true
ureq.workspace = true
url.workspace = true

[target.'cfg(unix)'.dependencies]
filedescriptor.workspace = true
rustix = { version = "=1.1.4", features = ["fs", "process", "termios"] }

[target.'cfg(windows)'.dependencies]
crossterm.workspace = true

[dev-dependencies]
rstest.workspace = true
assert_fs.workspace = true
pretty_assertions.workspace = true
proptest.workspace = true
proptest-derive.workspace = true
static_assertions.workspace = true

[lints]
workspace = true
